[build]
  publish = "public"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
# For Plausible proxying:
# https://plausible.io/docs/proxy/guides/netlify#troubleshooting
[build.processing.js]
  bundle = false
  minify = false

# Plausible
[[redirects]]
  from = "/apple-strudel/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
[[redirects]]
  from = "/apple-strudel/api/event"
  to = "https://plausible.io/api/event"
  status = 200
